name: OMG_genML-CPU
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.21
  - pip=25.0.1
  - setuptools=75.8.2
  - wheel=0.45.1
  - ca-certificates=2025.1.31
  - pip:
    - torch==2.2.0
    - dask==2024.7.1
    - absl-py==2.2.1
    - alembic==1.15.2
    - annotated-types==0.7.0
    - blinker==1.9.0
    - blis==1.2.0
    - bokeh==3.4.3
    - botorch==0.10.0
    - catalogue==2.0.10
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cloudpathlib==0.21.0
    - cloudpickle==3.1.1
    - colorama==0.4.6
    - colorlog==6.9.0
    - confection==0.1.5
    - configargparse==1.7
    - contourpy==1.3.0
    - ctranslate2==4.5.0
    - cycler==0.12.1
    - cymem==2.0.11
    - dask-expr==1.1.9
    - distributed==2024.7.1
    - docstring-parser==0.16
    - filelock==3.13.1
    - flask==3.1.0
    - fonttools==4.56.0
    - fsspec==2024.6.1
    - future==1.0.0
    - gpytorch==1.11
    - greenlet==3.1.1
    - grpcio==1.71.0
    - hyperopt==0.2.7
    - idna==3.10
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - itsdangerous==2.2.0
    - jaxtyping==0.2.36
    - jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - langcodes==3.5.0
    - language-data==1.3.0
    - linear-operator==0.5.1
    - llvmlite==0.43.0
    - locket==1.0.0
    - lxml==5.3.1
    - lz4==4.4.3
    - mako==1.3.9
    - marisa-trie==1.2.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.4
    - mdurl==0.1.2
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multipledispatch==1.0.0
    - murmurhash==1.0.12
    - mypy-extensions==1.1.0
    - networkx==3.2.1
    - numba==0.60.0
    - numpy==1.26.4
    - opennmt-py==3.5.1
    - opt-einsum==3.4.0
    - optuna==4.2.1
    - packaging==24.2
    - pandas==2.2.3
    - partd==1.4.2
    - pillow==11.1.0
    - portalocker==3.1.1
    - preshed==3.0.9
    - protobuf==6.30.2
    - psutil==7.0.0
    - py4j==0.10.9.9
    - pyahocorasick==2.1.0
    - pyarrow==19.0.1
    - pyarrow-hotfix==0.6
    - pybind11==2.13.6
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygments==2.19.1
    - pyonmttok==1.37.1
    - pyparsing==3.2.3
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - rapidfuzz==3.12.2
    - rdkit==2024.3.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - sacrebleu==2.5.1
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - seaborn==0.13.2
    - shellingham==1.5.4
    - six==1.17.0
    - smart-open==7.1.0
    - sortedcontainers==2.4.0
    - spacy==3.8.3
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - sqlalchemy==2.0.40
    - srsly==2.5.1
    - sympy==1.13.1
    - tabulate==0.9.0
    - tblib==3.1.0
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - thinc==8.3.4
    - threadpoolctl==3.6.0
    - toolz==1.0.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - typed-argument-parser==1.10.1
    - typeguard==2.13.3
    - typer==0.15.2
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - tzdata==2025.2
    - urllib3==2.3.0
    - waitress==3.0.2
    - wasabi==1.1.3
    - weasel==0.4.1
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - xyzservices==2025.1.0
    - zict==3.0.0
    - zipp==3.21.0
